### ISSUE TITLE
Document the different versions of the meshes for Sawyer

### ISSUE THREAD

**Issue by fumin** [RethinkRobotics/sawyer_robot#27]
Currently, this repo contain two versions of the meshes for the Sawyer robot:

https://github.com/RethinkRobotics/sawyer_robot/tree/master/sawyer_description/meshes/sawyer_ft
https://github.com/RethinkRobotics/sawyer_robot/tree/master/sawyer_description/meshes/sawyer_pv

Both meshes have similar latest commit time, which suggests that both are actively maintained.
Closer inspection suggests that "sawyer_pv" is generated by solidworks, and "sawyer_ft" by Meshlab.
However, it is not clear what further practical difference this would lead to.

Some sort of documentation explaining the difference between the two, and guidelines to choose either one would be helpful.

**Comment by IanTheEngineer** [comment]
Hi @fumin. I have abstracted most of this away from the SDK customer to simply "just work" with their robot, regardless of its hardware model. That allows this package to be a "one-package-fits-all-sawyers" solution. However, I am happy to explain the method to this madness. This repo actually contains **four** versions of meshes for the Sawyer robot, according to the different stages of the development for the Sawyer robot:
- `ft` = Field test. These models only exist at Rethink HQ. You can safely ignore all meshes here
- `pv` = Product Version. This is the product run of Sawyer.
- `mp1` and `mp3` = Mass production versions. As new tooling comes about, slight changes are made to some of the shells of Sawyer and their meshes. The kinematic impacts are minimal an reflected in the URDF. There are also `mp2` and `mp4` models, but `mp2` uses the same meshes as `mp1`, and `mp4` uses the same meshes as `mp3`.

You will find that each new robot "overlays" the previous robot model meshes, with some updates. For instance, the `mp3` robot uses new `l0` and `l1` meshes itself, as well as `l6` meshes from `mp1`, and then every other mesh from `pv`. This is always specified by your real robot's `URDF`:
`$ rosparam get -p /robot_description | tail -n +2 > your_sawyer.urdf`

Alternatively, you can use the generic Sawyer urdf (an `mp3` model) that we've supplied in this repository:
https://github.com/RethinkRobotics/sawyer_robot/blob/master/sawyer_description/urdf/sawyer.urdf

A whole bunch of abstraction here, but I hope this clears things up for you a bit. The gist is that these robot models shouldn't matter to the end user, as the robot will function the same regardless of the model you have. And you'll need to grab a few meshes from each folder according to your robot's model and `URDF`. If you're curious, robot model can be queried from the parameter server too:
```
$ rosparam get /manifest/robot_model
mp2
```

**Comment by fumin** [comment]
Hi Ian

Thanks for this wonderful explanation, we have a much clearer picture of the robot models contained in this repo now.
Moreover, I believe the whole community would benefit a lot if this information is included say in the README.
That said, since we are able to go forward with this information, I would be closing this issue for now.
Thanks again for your input.
