### ISSUE TITLE
sawyer.urdf does not work in Gazebo

### ISSUE THREAD

**Issue by kuniyuki-takahashi** [RethinkRobotics/sawyer_robot#43]
I cannot open sawyer.urdf in Gazebo with command 
# rosrun gazebo_ros spawn_model -file `rospack find sawyer_description`/urdf/sawyer.urdf -urdf -model sawyer
The model works after I change 
<box size = "0.00 0.00 0.00"> -> <box size = "0.01 0.01 0.01">

**Comment by IanTheEngineer** [comment]
Are you intending to just view Sawyer in Gazebo, or simulate it with physics?

The integration with Sawyer in Gazebo is happening in the `development` branch. The `sawyer_gazebo` repository is currently closed source (but will be open sourced upon release).

**Comment by kuniyuki-takahashi** [comment]
I try to simulate Sawyer in Gazebo with physics.

I see. Thank you.

**Comment by IanTheEngineer** [comment]
Ok, closing this issue for now. I will post an announcement on [discourse.ros.org](discourse.ros.org) along with the Baxter & Sawyer forums when `sawyer_gazebo` is released. Closing this for now
